# Generated by Django 3.2.9 on 2021-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.CharField(
                        choices=[("WS", "Winter semester"), ("SS", "Summer semester")],
                        default="WS",
                        max_length=2,
                        verbose_name="Semester",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
            ],
            options={
                "ordering": ["year", "semester"],
                "unique_together": {("semester", "year")},
            },
        ),
    ]
