# Generated by Django 3.2.9 on 2021-11-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_idea"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Semester",
        ),
    ]
