name: dependabot for pre-commit

on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron: '0 19 * * 5' # monthly

    workflow_dispatch:

jobs:
    update_pre-commit:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-python@v2.3.2
              with:
                  python-version: 3.9
                  cache: 'pip'
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit
            - name: install update pre-commit
              run: |
                  pre-commit autoupdate
                  pre-commit autoupdate --config .pre-commit-only-line-endings-config.yaml
            - name: Commit pre-commit file if changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Automated Change: updated pre-commit requirements'
